/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTabOrderRouteImport } from './routes/api/tab-order'
import { Route as ApiSyncAssignmentsRouteImport } from './routes/api/sync-assignments'
import { Route as ApiSuggestionsRouteImport } from './routes/api/suggestions'
import { Route as ApiParseDocumentRouteImport } from './routes/api/parse-document'
import { Route as ApiMentorDocumentsRouteImport } from './routes/api/mentor-documents'
import { Route as ApiLitwitsDocsRouteImport } from './routes/api/litwits-docs'
import { Route as ApiLitwitsDocVersionsRouteImport } from './routes/api/litwits-doc-versions'
import { Route as ApiLitwitsDocSyncRouteImport } from './routes/api/litwits-doc-sync'
import { Route as ApiLitwitsDocActivityRouteImport } from './routes/api/litwits-doc-activity'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiGoogleSheetsFetchRouteImport } from './routes/api/google-sheets-fetch'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiDocSyncRouteImport } from './routes/api/doc-sync'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiArsrSheetsRouteImport } from './routes/api/arsr-sheets'
import { Route as ApiArEnrichRouteImport } from './routes/api/ar-enrich'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTabOrderRoute = ApiTabOrderRouteImport.update({
  id: '/api/tab-order',
  path: '/api/tab-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncAssignmentsRoute = ApiSyncAssignmentsRouteImport.update({
  id: '/api/sync-assignments',
  path: '/api/sync-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: '/api/suggestions',
  path: '/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseDocumentRoute = ApiParseDocumentRouteImport.update({
  id: '/api/parse-document',
  path: '/api/parse-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorDocumentsRoute = ApiMentorDocumentsRouteImport.update({
  id: '/api/mentor-documents',
  path: '/api/mentor-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLitwitsDocsRoute = ApiLitwitsDocsRouteImport.update({
  id: '/api/litwits-docs',
  path: '/api/litwits-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLitwitsDocVersionsRoute = ApiLitwitsDocVersionsRouteImport.update({
  id: '/api/litwits-doc-versions',
  path: '/api/litwits-doc-versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLitwitsDocSyncRoute = ApiLitwitsDocSyncRouteImport.update({
  id: '/api/litwits-doc-sync',
  path: '/api/litwits-doc-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLitwitsDocActivityRoute = ApiLitwitsDocActivityRouteImport.update({
  id: '/api/litwits-doc-activity',
  path: '/api/litwits-doc-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleSheetsFetchRoute = ApiGoogleSheetsFetchRouteImport.update({
  id: '/api/google-sheets-fetch',
  path: '/api/google-sheets-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocSyncRoute = ApiDocSyncRouteImport.update({
  id: '/api/doc-sync',
  path: '/api/doc-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArsrSheetsRoute = ApiArsrSheetsRouteImport.update({
  id: '/api/arsr-sheets',
  path: '/api/arsr-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArEnrichRoute = ApiArEnrichRouteImport.update({
  id: '/api/ar-enrich',
  path: '/api/ar-enrich',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sales': typeof SalesRoute
  '/student': typeof StudentRoute
  '/api/ar-enrich': typeof ApiArEnrichRoute
  '/api/arsr-sheets': typeof ApiArsrSheetsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/doc-sync': typeof ApiDocSyncRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/google-sheets-fetch': typeof ApiGoogleSheetsFetchRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/litwits-doc-activity': typeof ApiLitwitsDocActivityRoute
  '/api/litwits-doc-sync': typeof ApiLitwitsDocSyncRoute
  '/api/litwits-doc-versions': typeof ApiLitwitsDocVersionsRoute
  '/api/litwits-docs': typeof ApiLitwitsDocsRoute
  '/api/mentor-documents': typeof ApiMentorDocumentsRoute
  '/api/parse-document': typeof ApiParseDocumentRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/sync-assignments': typeof ApiSyncAssignmentsRoute
  '/api/tab-order': typeof ApiTabOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sales': typeof SalesRoute
  '/student': typeof StudentRoute
  '/api/ar-enrich': typeof ApiArEnrichRoute
  '/api/arsr-sheets': typeof ApiArsrSheetsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/doc-sync': typeof ApiDocSyncRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/google-sheets-fetch': typeof ApiGoogleSheetsFetchRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/litwits-doc-activity': typeof ApiLitwitsDocActivityRoute
  '/api/litwits-doc-sync': typeof ApiLitwitsDocSyncRoute
  '/api/litwits-doc-versions': typeof ApiLitwitsDocVersionsRoute
  '/api/litwits-docs': typeof ApiLitwitsDocsRoute
  '/api/mentor-documents': typeof ApiMentorDocumentsRoute
  '/api/parse-document': typeof ApiParseDocumentRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/sync-assignments': typeof ApiSyncAssignmentsRoute
  '/api/tab-order': typeof ApiTabOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/sales': typeof SalesRoute
  '/student': typeof StudentRoute
  '/api/ar-enrich': typeof ApiArEnrichRoute
  '/api/arsr-sheets': typeof ApiArsrSheetsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/doc-sync': typeof ApiDocSyncRoute
  '/api/documents': typeof ApiDocumentsRoute
  '/api/google-sheets-fetch': typeof ApiGoogleSheetsFetchRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/litwits-doc-activity': typeof ApiLitwitsDocActivityRoute
  '/api/litwits-doc-sync': typeof ApiLitwitsDocSyncRoute
  '/api/litwits-doc-versions': typeof ApiLitwitsDocVersionsRoute
  '/api/litwits-docs': typeof ApiLitwitsDocsRoute
  '/api/mentor-documents': typeof ApiMentorDocumentsRoute
  '/api/parse-document': typeof ApiParseDocumentRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/sync-assignments': typeof ApiSyncAssignmentsRoute
  '/api/tab-order': typeof ApiTabOrderRoute
  '/api/users': typeof ApiUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/mentor'
    | '/projects'
    | '/resume'
    | '/sales'
    | '/student'
    | '/api/ar-enrich'
    | '/api/arsr-sheets'
    | '/api/auth'
    | '/api/comments'
    | '/api/doc-sync'
    | '/api/documents'
    | '/api/google-sheets-fetch'
    | '/api/leads'
    | '/api/litwits-doc-activity'
    | '/api/litwits-doc-sync'
    | '/api/litwits-doc-versions'
    | '/api/litwits-docs'
    | '/api/mentor-documents'
    | '/api/parse-document'
    | '/api/suggestions'
    | '/api/sync-assignments'
    | '/api/tab-order'
    | '/api/users'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/mentor'
    | '/projects'
    | '/resume'
    | '/sales'
    | '/student'
    | '/api/ar-enrich'
    | '/api/arsr-sheets'
    | '/api/auth'
    | '/api/comments'
    | '/api/doc-sync'
    | '/api/documents'
    | '/api/google-sheets-fetch'
    | '/api/leads'
    | '/api/litwits-doc-activity'
    | '/api/litwits-doc-sync'
    | '/api/litwits-doc-versions'
    | '/api/litwits-docs'
    | '/api/mentor-documents'
    | '/api/parse-document'
    | '/api/suggestions'
    | '/api/sync-assignments'
    | '/api/tab-order'
    | '/api/users'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/login'
    | '/mentor'
    | '/projects'
    | '/resume'
    | '/sales'
    | '/student'
    | '/api/ar-enrich'
    | '/api/arsr-sheets'
    | '/api/auth'
    | '/api/comments'
    | '/api/doc-sync'
    | '/api/documents'
    | '/api/google-sheets-fetch'
    | '/api/leads'
    | '/api/litwits-doc-activity'
    | '/api/litwits-doc-sync'
    | '/api/litwits-doc-versions'
    | '/api/litwits-docs'
    | '/api/mentor-documents'
    | '/api/parse-document'
    | '/api/suggestions'
    | '/api/sync-assignments'
    | '/api/tab-order'
    | '/api/users'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  SalesRoute: typeof SalesRoute
  StudentRoute: typeof StudentRoute
  ApiArEnrichRoute: typeof ApiArEnrichRoute
  ApiArsrSheetsRoute: typeof ApiArsrSheetsRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiDocSyncRoute: typeof ApiDocSyncRoute
  ApiDocumentsRoute: typeof ApiDocumentsRoute
  ApiGoogleSheetsFetchRoute: typeof ApiGoogleSheetsFetchRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLitwitsDocActivityRoute: typeof ApiLitwitsDocActivityRoute
  ApiLitwitsDocSyncRoute: typeof ApiLitwitsDocSyncRoute
  ApiLitwitsDocVersionsRoute: typeof ApiLitwitsDocVersionsRoute
  ApiLitwitsDocsRoute: typeof ApiLitwitsDocsRoute
  ApiMentorDocumentsRoute: typeof ApiMentorDocumentsRoute
  ApiParseDocumentRoute: typeof ApiParseDocumentRoute
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute
  ApiSyncAssignmentsRoute: typeof ApiSyncAssignmentsRoute
  ApiTabOrderRoute: typeof ApiTabOrderRoute
  ApiUsersRoute: typeof ApiUsersRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tab-order': {
      id: '/api/tab-order'
      path: '/api/tab-order'
      fullPath: '/api/tab-order'
      preLoaderRoute: typeof ApiTabOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-assignments': {
      id: '/api/sync-assignments'
      path: '/api/sync-assignments'
      fullPath: '/api/sync-assignments'
      preLoaderRoute: typeof ApiSyncAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggestions': {
      id: '/api/suggestions'
      path: '/api/suggestions'
      fullPath: '/api/suggestions'
      preLoaderRoute: typeof ApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-document': {
      id: '/api/parse-document'
      path: '/api/parse-document'
      fullPath: '/api/parse-document'
      preLoaderRoute: typeof ApiParseDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor-documents': {
      id: '/api/mentor-documents'
      path: '/api/mentor-documents'
      fullPath: '/api/mentor-documents'
      preLoaderRoute: typeof ApiMentorDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/litwits-docs': {
      id: '/api/litwits-docs'
      path: '/api/litwits-docs'
      fullPath: '/api/litwits-docs'
      preLoaderRoute: typeof ApiLitwitsDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/litwits-doc-versions': {
      id: '/api/litwits-doc-versions'
      path: '/api/litwits-doc-versions'
      fullPath: '/api/litwits-doc-versions'
      preLoaderRoute: typeof ApiLitwitsDocVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/litwits-doc-sync': {
      id: '/api/litwits-doc-sync'
      path: '/api/litwits-doc-sync'
      fullPath: '/api/litwits-doc-sync'
      preLoaderRoute: typeof ApiLitwitsDocSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/litwits-doc-activity': {
      id: '/api/litwits-doc-activity'
      path: '/api/litwits-doc-activity'
      fullPath: '/api/litwits-doc-activity'
      preLoaderRoute: typeof ApiLitwitsDocActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-sheets-fetch': {
      id: '/api/google-sheets-fetch'
      path: '/api/google-sheets-fetch'
      fullPath: '/api/google-sheets-fetch'
      preLoaderRoute: typeof ApiGoogleSheetsFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-sync': {
      id: '/api/doc-sync'
      path: '/api/doc-sync'
      fullPath: '/api/doc-sync'
      preLoaderRoute: typeof ApiDocSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/arsr-sheets': {
      id: '/api/arsr-sheets'
      path: '/api/arsr-sheets'
      fullPath: '/api/arsr-sheets'
      preLoaderRoute: typeof ApiArsrSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ar-enrich': {
      id: '/api/ar-enrich'
      path: '/api/ar-enrich'
      fullPath: '/api/ar-enrich'
      preLoaderRoute: typeof ApiArEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  SalesRoute: SalesRoute,
  StudentRoute: StudentRoute,
  ApiArEnrichRoute: ApiArEnrichRoute,
  ApiArsrSheetsRoute: ApiArsrSheetsRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiDocSyncRoute: ApiDocSyncRoute,
  ApiDocumentsRoute: ApiDocumentsRoute,
  ApiGoogleSheetsFetchRoute: ApiGoogleSheetsFetchRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLitwitsDocActivityRoute: ApiLitwitsDocActivityRoute,
  ApiLitwitsDocSyncRoute: ApiLitwitsDocSyncRoute,
  ApiLitwitsDocVersionsRoute: ApiLitwitsDocVersionsRoute,
  ApiLitwitsDocsRoute: ApiLitwitsDocsRoute,
  ApiMentorDocumentsRoute: ApiMentorDocumentsRoute,
  ApiParseDocumentRoute: ApiParseDocumentRoute,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
  ApiSyncAssignmentsRoute: ApiSyncAssignmentsRoute,
  ApiTabOrderRoute: ApiTabOrderRoute,
  ApiUsersRoute: ApiUsersRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
